version: '3.4'

services:

    
    hello-xml:
       build:
        context: .
        dockerfile: ../hello_xml/Dockerfile        
       image: hello_rest_xml_bal
       ports:
            - "9093:9090"
        
       
        
       
    world-xml:
       build:
        context: .
        dockerfile:  ../world_xml/Dockerfile
       image: world_rest_xml_bal
       ports:
            - "9094:9090"
       
       