version: '3.4'

services:
    
    rabbitmq:
        image: rabbitmq:3
        ports: 
            - "15672:15672"
            - "5672:5672"
    
    hello:
       build:
        context: .
        dockerfile: ../hello_json/Dockerfile        
       image: hello_amqp_json_java
       ports:
            - "8081:8080"
        
       
    world:
       build:
        context: .
        dockerfile:  ../world_json/Dockerfile
       image: world_amqp_json_java
       
       
       