version: '3.4'

services:

    
    hello:
       build:
        context: .
        dockerfile: ../hello/Dockerfile        
       image: hello_grpc_bal
       
        
       
        
       
    world:
       build:
        context: .
        dockerfile:  ../world/Dockerfile
       image: world_grpc_bal
       ports:
            - "9092:9090"
       
       