version: '3.4'

services:

    rabbitmq:
        image: rabbitmq:3
        ports: 
            - "15672:15672"
            - "5672:5672"

    
    hello:
       build:
        context: .
        dockerfile: ../hello_json/Dockerfile        
       image: hello_amqp_json_bal
       ports:
            - "9091:9090"
        
        
       
        
       
    world:
       build:
        context: .
        dockerfile:  ../world_json/Dockerfile
       image: world_amqp_json_bal
       depends_on: 
            - "hello"
       
       
       