version: '3.4'

services:

    
    hello:
       build:
        context: .
        dockerfile: ../hello/Dockerfile        
       image: hello_rest_json_jolie
       ports:
            - "8001:8000"
        
       
    world:
       build:
        context: .
        dockerfile:  ../world/Dockerfile
       image: world_rest_json_jolie
       ports:
           - "8002:8000"
       
       